### ISSUE TITLE
PushNotifications invalid project files in 06-server-side-pushes folder.

### ISSUE THREAD

**Issue by jaramirez1729** [raywenderlich/not-materials#2]
The **PushNotifications** project located in "05-apple-push-notification-servers/projects/starter/PushNotifications" is an iOS project which we created in Chapter 4 first.

In "06-server-side-pushes/projects/starter/PushNotifications", the  **PushNotifications** project located in the final and starter folders is a Swift Package project, not the same iOS project from Chapter 4/5.

The final and starter projects in "07-expanding-the-application/projects/starter/PushNotifications" are iOS projects, no Swift Package projects.

So in what part of the book between chapter 5 to 6 did we convert the **PushNotifications** project to a Swift Package project and then back to an iOS project in Chapter 7? This means chapter 6 directory is missing the correct **PushNotifications** project files and looks like it contains duplicates of the WebService project.

**Comment by marinbenc** [comment]
Hi @jaramirez1729 I see that you closed this issue. Is this still a problem or?
